### ISSUE TITLE
Pass extra docker specific parameters

### ISSUE THREAD

**Issue by jgoux** [mkenney/docker-npm#167] opened 2018-10-17 13:36 UTC
Hello,

There are use cases where it would be useful to be able to pass extra parameters to the underlying `docker run` command.

For example to expose a specific port at runtime (when working with web servers).

This is how I did it : 
```diff
#!/usr/bin/env sh

TAG=node-10-alpine
if [ "" != "$DOCKER_NPM_TAG" ]; then
    TAG="$DOCKER_NPM_TAG"
fi
SCRIPT=yarn
INSTALL_SCRIPT=https://raw.githubusercontent.com/mkenney/docker-npm/master/bin/install.sh

if [ "self-update" = "$1" ]; then
    docker pull mkenney/npm:$TAG
    curl -f -L -s $INSTALL_SCRIPT | sh -s $SCRIPT $TAG $(dirname $0)
else
    if [ -t 0 ]; then
        term_type=ti
    else
        term_type=i
    fi

+    DOCKER_ARGS=""
+    YARN_ARGS=${@#* -- }
+
+    case "$@" in
+        *" -- "*) DOCKER_ARGS=${@% -- *};;
+    esac

    docker run \
        --rm \
        -$term_type \
        -v $HOME/.cache/yarn:/home/dev/.cache/yarn:rw \
        -v $(pwd):/src:rw \
        -v $HOME/.ssh:/home/dev/.ssh:ro \
+        $DOCKER_ARGS \
+        mkenney/npm:$TAG /usr/local/bin/$SCRIPT $YARN_ARGS
fi
```

Usage : `yarn -p 3000:3000 -- start`

**Comment by mkenney** [comment] 2018-10-18 03:14
Hi! Thank you for opening some issues and for taking a look, it's been a busy couple of weeks so I'm not sure when I'll have a chance to give this some attention, probably this weekend (PRs are most welcome!).

I didn't know github had diff highlighting, that's cool.

That's a good idea, though I think I'm more in favor of something like:
```diff
--- a/bin/yarn
+++ b/bin/yarn
@@ -1,27 +1,28 @@
     docker run \
         --rm \
         -$term_type \
         -v $(pwd):/src:rw \
         -v $HOME/.ssh:/home/dev/.ssh:ro \
+        $DOCKER_NPM_ARGS \
         mkenney/npm:$TAG /usr/local/bin/$SCRIPT $@
 fi
 ```

Then you would use it like `DOCKER_NPM_ARGS="-p 3000:3000" yarn start`. I think flags that affect the container or it's environment probably shouldin't be mixed in with a commands normal arguments. What do you think?

**Comment by mkenney** [comment] 2018-10-18 05:01
Actually, I think that might solve the [cache issue](#166) you mentioned too because you should be able to do
```
DOCKER_NPM_ARGS="-v $HOME/.npm:/home/dev/.npm:rw" npm cache add <whatever>
```

**Comment by jgoux** [comment] 2018-10-18 06:37
Sure, I wasn't sure about the syntax at all, and the env variable approach is better so we don't alter the CLIs API. 👍

**Comment by jgoux** [comment] 2018-10-19 08:09
I also noticed that environment variables are not forwarded.

Am I doing it wrong?

`docker run -it --rm -e TEST=4000 mkenney/npm:node-10-alpine echo $TEST`

**Comment by mkenney** [comment] 2018-10-19 17:17
That is actually slightly tricky. The issue is that, in order to make sure files aren't created as `root` on linux systems, the entrypoint runs the commands in a sub-shell running as an appropriate `uid`/`gid`. The problem is that the container environment variables aren't passed to that shell, the only solution I know of at the moment is to bypass the subshell by overriding the entrypoint using `--entrypoint=""`.

Also, echoing `$TEST` like that won't work because you're mixing variables in your current shell with variables in your container (`$TEST` is evaluated before being passed as a docker argument). So, for your example, you would have to do something like 

```
docker run --rm -it --entrypoint="" -e TEST=4000 mkenney/npm:node-10-alpine env | grep TEST
```

The trade-off is that the `uid` and `gid` the process will run as are both `0`.

**Comment by mkenney** [comment] 2018-10-22 00:51
@jgoux I've implemented the docker arguments feature in the latest scripts as [described above](https://github.com/mkenney/docker-npm/issues/167#issuecomment-430861154). Please let me know if that works for you or if there are any problems. Thanks

**Comment by mkenney** [comment] 2018-12-07 04:22
Closing, feel free to reopen.

**Closed as completed by mkenney** 2018-12-07 04:22 UTC
Labels: enhancement

**Comment by jgoux** [comment] 2018-12-07 07:13
Hey sorry for not giving feedbacks on all 3 issues.

This is all working great, thank you very much @mkenney ! 👏 ⭐️

**Comment by mkenney** [comment] 2018-12-07 20:32
Awesome, good to hear! Let me know if anything else comes up, thanks! 🎉
