### ISSUE TITLE
add yarn support?

### ISSUE THREAD

**Issue by toby1991** [mkenney/docker-npm#19] opened 2016-10-20 10:02 UTC
can we add yarn support?

it would be awesome!

**Comment by mkenney** [comment] 2016-10-20 22:28
[Done](20) and [done](21), thanks for the suggestion! `alpine` takes a while to build so that image should be ready on [DockerHub](https://hub.docker.com/r/mkenney/npm/) in an hour or so but the `debian` image is ready now.

**Comment by bennypowers** [comment] 2016-11-22 01:12
i got errors like `error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/root/.cache/yarn/npm-test-fixture-1.1.1-3c513859eea8afbf18ee342771b62ad143533166'".` when trying to `yarn global add foo` using alpine-7.0

**Comment by mkenney** [comment] 2016-11-22 02:00
@bennyp123 Thanks for reporting that, I'm taking a look to see if I can reproduce it.

**Comment by mkenney** [comment] 2016-11-22 02:48
Hi @bennyp123,

There are two issues here, the first is that there is an [upstream issue with `yarn-v0.17.2`](https://github.com/mkenney/docker-npm/issues/76) which has been fixed in `v0.17.4` and `v0.17.8` appears to be available. It looks like some of the hub.docker.com images haven't been refreshed in a few days so I'm going to trigger new builds now but the process may take a few hours. I may look into setting up scheduled builds so that doesn't happen again.

The second issue is that unfortunately you can't do global installs using this project. When you run any of these scripts your project folder is "shared" with a virtual machine so anything that gets written to your project folder is saved to the hard drive but if you write files anywhere else they're saved in the virtual machine which is destroyed when the command ends, so each time you run it you run it without any of the changes.

Your best choices are to either install things locally and execute them that way (i.e. `./node_modules/foo/bin/foo`) or to extend this project with your own `Dockerfile` and add whichever additional tools you need. I'm also happy to add more commonly used tools to this project.

Give it a few hours and run the `yarn self-update` command to get the new image, hopefully that will fix the `yarn` exception. And please let me know if you still have any trouble.

**Comment by bennypowers** [comment] 2016-11-22 02:51
Hey thanks for checking this out. 

> The second issue is that unfortunately you can't do global installs using this project. When you run any of these scripts your project folder is "shared" with a virtual machine so anything that gets written to your project folder is saved to the hard drive but if you write files anywhere else they're saved in the virtual machine which is destroyed when the command ends, so each time you run it you run it without any of the changes.

my builds are passing when i run `npm i -g foo` so for my relatively simple use case what would be the difference using yarn? further to that, using node:latest; npm -i g yarn; yarn global add foo was fine. help me to understand

**Comment by mkenney** [comment] 2016-11-22 05:19
@bennyp123 Given your description I think there's some confusion. I don't think when you run the `npm` or `yarn` commands in your example that you are running the scripts in this project. That looks more like you're running locally installed versions.

In this project, if you run `npm i -g yarn` you get a permissions error because it's not running as root inside the container:
```
mkenney@9c0-docker$ ./bin/npm i -g yarn
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/yarn/node_modules/debug
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/yarn/node_modules/mime-db
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/yarn/node_modules/mime-types
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/yarn/node_modules/node-uuid
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/yarn/node_modules/request
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/yarn/node_modules/object-path
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/yarn
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/yarn/node_modules
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
- node-uuid@1.4.7 node_modules/yarn/node_modules/node-uuid
/usr/local/lib
└─┬ yarn@0.17.8
  ├── debug@2.3.3
  ├── object-path@0.11.3
  └─┬ request@2.79.0
    ├─┬ mime-types@2.1.13
    │ └── mime-db@1.25.0
    └── uuid@3.0.0

npm ERR! Linux 4.8.3-x86_64-linode76
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "yarn"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.9
npm ERR! path /usr/local/lib/node_modules/yarn/node_modules/debug
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/yarn/node_modules/debug'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules/yarn/node_modules/debug'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/yarn/node_modules/debug' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /src/npm-debug.log
```

If you do happen to run that command in a folder owned by root (because the scripts run as a user that owns the current folder) it would succeed but it wouldn't actually install on the host system. Instead it would install into the Docker container and exit:

```
root@9c0-docker# ~mkenney/docker-tools/docker-npm/bin/npm i -g yarn
/usr/local/bin/yarn -> /usr/local/lib/node_modules/yarn/bin/yarn.js
/usr/local/bin/yarnpkg -> /usr/local/lib/node_modules/yarn/bin/yarn.js
- node-uuid@1.4.7 node_modules/yarn/node_modules/node-uuid
/usr/local/lib
└─┬ yarn@0.17.8
  ├── debug@2.3.3
  ├── object-path@0.11.3
  └─┬ request@2.79.0
    ├─┬ mime-types@2.1.13
    │ └── mime-db@1.25.0
    └── uuid@3.0.0

root@9c0-docker# yarn
-bash: yarn: command not found
```

That's because it runs in a virtual machine that never saves anything. This is confusing for a lot of people that I work with so I'll write up an example I can link to and share with them (and you :). Sorry if you already know most of this.

# how it works...
First, you must have [Docker installed](https://docs.docker.com/engine/installation/) to use this project, and you probably want to be able to [run docker without sudo](https://docs.docker.com/engine/installation/linux/ubuntulinux/#/create-a-docker-group).

Once that's setup, you can run the `mkenney/npm` image in a Docker container and run the commands by hand which may be easier to understand:
```sh
# first, start the virtual machine and open a shell
mkenney@9c0-docker$ docker run -ti mkenney/npm:7.0-alpine sh

# now you will be logged in to the running `mkenney/npm:7.0-alpine` docker container
# as root:
/src# whoami
root
/src#

# `yarn` is already installed in the image so I'll use jshint as my example
/src# jshint
sh: jshint: not found
/src# npm i -g jshint
/usr/local/bin/jshint -> /usr/local/lib/node_modules/jshint/bin/jshint
/usr/local/lib
└─┬ jshint@2.9.4
  ├─┬ cli@1.0.1
  │ └─┬ glob@7.1.1
  │   ├── fs.realpath@1.0.0
  │   ├─┬ inflight@1.0.6
  │   │ └── wrappy@1.0.2
  │   ├── inherits@2.0.3
  │   ├── once@1.4.0
  │   └── path-is-absolute@1.0.1
  ├─┬ console-browserify@1.1.0
  │ └── date-now@0.1.4
  ├── exit@0.1.2
  ├─┬ htmlparser2@3.8.3
  │ ├── domelementtype@1.3.0
  │ ├── domhandler@2.3.0
  │ ├─┬ domutils@1.5.1
  │ │ └─┬ dom-serializer@0.1.0
  │ │   ├── domelementtype@1.1.3
  │ │   └── entities@1.1.1
  │ ├── entities@1.0.0
  │ └─┬ readable-stream@1.1.14
  │   ├── core-util-is@1.0.2
  │   ├── isarray@0.0.1
  │   └── string_decoder@0.10.31
  ├── lodash@3.7.0
  ├─┬ minimatch@3.0.3
  │ └─┬ brace-expansion@1.1.6
  │   ├── balanced-match@0.4.2
  │   └── concat-map@0.0.1
  ├── shelljs@0.3.0
  └── strip-json-comments@1.0.4

/src#jshint --version
jshint v2.9.4
/src#

# `jshint` is clearly installed, so now exit the virtual machine and restart it
/src# exit

mkenney@9c0-docker$

# now just go back in and try to run the jshint command
mkenney@9c0-docker$ docker run -ti mkenney/npm:7.0-alpine sh

/src# jshint
sh: jshint: not found
/src#
```

The reason for this is that Docker runs the image in memory and starts it from scratch each time so once it exits any changes are gone. You can share the filesystem with the running image (using the `-v` flag) when you start the image container and save any output that way:

```sh
mkenney@9c0-docker$ mkdir tmp && cd tmp && echo "Hello from the host" > test.txt
mkenney@9c0-docker$ docker run -ti -v $(pwd):/src:rw mkenney/npm:7.0-alpine sh
/src# cat test.txt
Hello from the host
/src# echo "Hello from Docker" > test.txt
/src# exit
mkenney@9c0-docker$ cat test.txt
Hello from Docker
mkenney@9c0-docker$
```

This project is the [`Dockerfile`](https://github.com/mkenney/docker-npm/blob/master/Dockerfile) and some [wrapper scripts](https://github.com/mkenney/docker-npm/tree/master/bin) for the image described above. The image includes a [command wrapper](https://github.com/mkenney/docker-scripts/blob/master/container/run-as-user) that allows it to write files to the mounted directory with the same `uid` and `gid` as the mounted directory. That way `npm` doesn't install everything as root. When you run [`npm` using the provided script](https://github.com/mkenney/docker-npm/blob/master/bin/npm) it's actually executing:
```sh
mkenney@docker-9c0$ docker run --rm -ti -v $(pwd):/src:rw -v $HOME/.ssh:/home/dev/.ssh:ro mkenney/npm:7.0-alpine /run-as-user /usr/local/bin/npm
```

with comments:
```sh
mkenney@docker-9c0$ set -x \

    # Tell docker to run an image in a container. If it doesn't exist locally docker will try
    # to download it automatically
    && docker run \

        # Delete the container automatically when it exits so you don't have to do any
        # manual housekeeping
        --rm \

        # Run in an interactive terminal. If you want to pipe input into the docker command
        # just use -i
        -ti \

        # Mount the current folder into the container when it starts in the /src folder and
        # make it writeable. You can use ':ro' instead of ':rw' to make it read-only
        -v $(pwd):/src:rw \

        # If there is a .ssh/ folder in your home directory this will attempt to mount it into
        # the container as a read-only volume. This is useful for accessing remote services
        # using public key authentication, accessing private GitHub repos for example.
        -v $HOME/.ssh:/home/dev/.ssh:ro \

        # Specify which docker image to run in the container
        mkenney/npm:7.0-alpine \

        # Everything after the image name is passed in as a command. This is a script that
        # will run the next command as a user who's user Id and group Id matches the
        # current directory. That way, any files written to the mounted volume will be written
        # with permissions that match that volume instead of root.
        /run-as-user \

        # Execute npm with any arguments passed 
        /usr/local/bin/npm
```

Because it's running in a virtual machine, it doesn't have access to any folders except for the one you run the command from. Because of that, global installs don't work.

**Comment by mkenney** [comment] 2016-11-23 04:30
This appears to be fixed and I've restored the `yarn` tests, [all branches are passing](https://travis-ci.org/mkenney/docker-npm/branches).

**Closed as completed by mkenney** 2016-11-23 04:30 UTC
